# Generated by Django 3.2 on 2022-03-17 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='airline',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.airline'),
        ),
    ]
