# Generated by Django 3.2 on 2022-03-17 09:01

import cases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case_docfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='docfile',
            field=models.FileField(blank=True, null=True, upload_to=cases.models.case_directory_path),
        ),
        migrations.AlterField(
            model_name='case',
            name='docfile',
            field=models.FileField(blank=True, null=True, upload_to=cases.models.case_directory_path),
        ),
    ]
