# Generated by Django 3.2 on 2022-03-17 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_auto_20220317_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMOSModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apn', models.IntegerField()),
                ('name', models.CharField(max_length=155)),
            ],
        ),
        migrations.AlterField(
            model_name='case',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.amosmodule'),
        ),
    ]
