# Generated by Django 3.2 on 2022-04-08 08:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0005_auto_20220317_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='emails_list',
            field=models.ManyToManyField(blank=True, related_name='cases', to=settings.AUTH_USER_MODEL),
        ),
    ]
